### ISSUE TITLE
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ...

### ISSUE THREAD

**Issue by Page-David** [taniwha/io_object_mu#17]
This is what I get when importing Kerbal X.craft:
> Traceback (most recent call last):
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_craft/import_craft.py", line 106, in execute
    return import_craft_op(self, context, **keywords)
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_craft/import_craft.py", line 80, in import_craft_op
    obj = import_craft(filepath)
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_craft/import_craft.py", line 60, in import_craft
    part = gamedata.parts[pname].get_model()
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_craft/part.py", line 64, in get_model
    self.cfg, loaded_parts_collection())
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/model/model.py", line 47, in compile_model
    mdl = db.model(submodelname)
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_craft/gamedata.py", line 153, in model
    self.models[url] = Model(path, url)
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/model/model.py", line 104, in __init__
    obj = import_mu(model, path, False, False)
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_mu/import_mu.py", line 187, in import_mu
    return process_mu(mu, os.path.dirname(filepath))
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_mu/import_mu.py", line 165, in process_mu
    create_textures(mu, mudir)
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_mu/textures.py", line 83, in create_textures
    load_image(base, e, path, tex.type)
  File "/home/page-david/.config/blender/2.80/scripts/addons/io_object_mu-master/import_mu/textures.py", line 66, in load_image
    img.colorspace_settings.name = 'Non-Color'
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('BT.1886 EOTF', 'Filmic Log Encoding', 'Linear', 'Non-Colour Data', 'sRGB EOTF')
>
>location: <unknown location>:-1
>
>location: <unknown location>:-1

And this is my blender version information (running blender -v):
>Blender 2.80 (sub 39)
	build date: 2019-01-02
	build time: 00:02:02
	build commit date: 2019-01-01
	build commit time: 15:44
	build hash: 4dd0a90f4213
	build platform: Linux
	build type: Release
	build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wnonnull -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable  -fuse-ld=gold -std=gnu11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
	build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Werror=implicit-function-declaration -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wuninitialized -Wundef -Wmissing-declarations  -fuse-ld=gold -std=c++11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
	build link flags:  -Wl,--version-script='/home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/creator/blender.map'
	build system: CMake

Also the git version of io_object_mu addon is cba88c5.

I tried this 2.79 version add-on with blender 2.79 and get similar error. So, what caused that?

**Comment by taniwha** [comment]
No idea, it's fine here (blender built from git).

**Comment by taniwha** [comment]
It appears this was fixed some time ago, probably in 60fee766d745dcebcf287482f08c88cc65e33279

**Comment by PixsaOJ** [comment]
This is not fixed, I am on Linux 2.93.3, and I have this issue with every model from Mixamo :/ Please help.

**Comment by luminarycrush** [comment]
This still exists in Blender 2.93.0, same exact error message.
