### ISSUE TITLE
Import Error: No color attribute

### ISSUE THREAD

**Issue by 321nick** [taniwha/io_object_mu#88]
![image](https://github.com/user-attachments/assets/6871f11f-36c1-46ed-849f-823689a914f9)

Got this when trying to import reliant_v2.mu from the squad directory. im on blender 2.9.1, and python 3.10.5

**Comment by popos123** [comment]
Should be fixed in my pull request (third tab from left on github).
I'm tested on: Windows 11, KSP 1.12.5, Blender 4.2, io_object_mu - my version from pull request
In that configuratiob should be only two warnings about scale:
![image](https://github.com/user-attachments/assets/56acb72e-93b9-4b05-8e78-5ad7a67b514a)

**Comment by pauverblom** [comment]
@popos123 I still get the same error using your PR in Mac, blender 3.0.1

**Comment by popos123** [comment]
I was give you even screenshot with working import, You can try on blender 3.6, 4.0, 4.1, 4.2, on that versions i was tested, in the attachement exported version:
[Reliant_v2.zip](https://github.com/user-attachments/files/16522206/Reliant_v2.zip)

**Comment by Bupher** [comment]
> Should be fixed in my pull request (third tab from left on github). I'm tested on: Windows 11, KSP 1.12.5, Blender 4.2, io_object_mu - my version from pull request In that configuratiob should be only two warnings about scale: ![image](https://github.com/user-attachments/assets/56acb72e-93b9-4b05-8e78-5ad7a67b514a)

Sorry to hijack this, but how did you get it to display the colors?

I am a total blender noob, but I got it to import the .mu files, but I cannot see the colors. I'd like to dump this into orca slicer and attempt to use the MMU to print this multicolor.|

![Image](https://github.com/user-attachments/assets/5fde4c9f-525c-41e5-88f9-845febafd2cd)

**Comment by popos123** [comment]
> > Should be fixed in my pull request (third tab from left on github). I'm tested on: Windows 11, KSP 1.12.5, Blender 4.2, io_object_mu - my version from pull request In that configuratiob should be only two warnings about scale: ![image](https://github.com/user-attachments/assets/56acb72e-93b9-4b05-8e78-5ad7a67b514a)
> 
> Sorry to hijack this, but how did you get it to display the colors?
> 
> I am a total blender noob, but I got it to import the .mu files, but I cannot see the colors. I'd like to dump this into orca slicer and attempt to use the MMU to print this multicolor.|
> 
> ![Image](https://github.com/user-attachments/assets/5fde4c9f-525c-41e5-88f9-845febafd2cd)

It is just a texture, on my screenshot in the upper left corner you can see the mu file and the texture file, and in blender is just switched to render mode with textures, so in orca slicer will be only one color.

Hmm, I've never tested, maybe it is possible to burn a texture into a 3D model??? Or more realistically a blender addon to slice a 3D model by texture depth / color and in orca slicer change filaments (colors) by 3D model parts???

**Comment by Bupher** [comment]
> > > Should be fixed in my pull request (third tab from left on github). I'm tested on: Windows 11, KSP 1.12.5, Blender 4.2, io_object_mu - my version from pull request In that configuratiob should be only two warnings about scale: ![image](https://github.com/user-attachments/assets/56acb72e-93b9-4b05-8e78-5ad7a67b514a)
> > 
> > 
> > Sorry to hijack this, but how did you get it to display the colors?
> > I am a total blender noob, but I got it to import the .mu files, but I cannot see the colors. I'd like to dump this into orca slicer and attempt to use the MMU to print this multicolor.|
> > ![Image](https://github.com/user-attachments/assets/5fde4c9f-525c-41e5-88f9-845febafd2cd)
> 
> It is just a texture, on my screenshot in the upper left corner you can see the mu file and the texture file, and in blender is just switched to render mode with textures, so in orca slicer will be only one color.
> 
> Hmm, I've never tested, maybe it is possible to burn a texture into a 3D model??? Or more realistically a blender addon to slice a 3D model by texture depth / color and in orca slicer change filaments (colors) by 3D model parts???

Yeah, when I import the .OBJ/.MTL, it prompts me to assign filaments to each color. It just only imports as one color.

![Image](https://github.com/user-attachments/assets/193ef554-998e-4ca5-8564-73ac14ab1921)
